name: Playwright Tests with Java

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adoptopenjdk'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://github.com/microsoft/playwright-java/releases/download/v1.24.0/playwright-java-1.24.0.zip
        unzip playwright-java-1.24.0.zip
        mvn clean install

    - name: Run Playwright and API Tests
      run: mvn test